name: Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run Docker container
      run: |
        docker-compose up -d
        
    - name: Wait for MySQL to be ready
      run: |
        docker-compose exec -T web bash -c 'while !</dev/tcp/db/3306; do sleep 1; done'

    - name: Run database migrations
      run: |
        docker-compose run web /rails/bin/rails db:create db:migrate

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Check if server is up

      run: |
        curl -s http://localhost:3000/api/v1/applications || exit 1

    - name: Run tests
      run: |
        python bin/chat_api_e2e_test.py 

    - name: Clean up
      run: |
        docker-compose down

